// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txsvlcraeewodeivmtde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4c3ZsY3JhZWV3b2RlaXZtdGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjM2NTgsImV4cCI6MjA2MjE5OTY1OH0.hrCdknjsNL3iFYGOFxl2GW-cX6IWFiyDdZ08TL0j5HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);